### PR TITLE
getData instead of all

### PR DESCRIPTION
**Pull request by fayland**
I do not find any function all in the slim code base and it seems getData works while all is not.

let me know if it's a wrong patch. (Twig seems using all() too)

Thanks

### CODE REVIEW

**Comment by fayland** [comment]
Sorry, I withdraw that.

**Comment by zymsys** [comment]
I ran into the same problem, and made the same change to make it work. Why was this withdrawn? Where does the all() method supposed to come from, and why is it prefered to getData()?

Thanks!

**Comment by silentworks** [comment]
What version of Slim are you using? Slim Views is only to be used with 2.3+.

**Comment by zymsys** [comment]
From my composer.lock:

```
        "name": "slim/slim",
        "version": "2.2.0",
```

...
            "name": "slim/views",
            "version": "0.1.0",

So I should be good as far as the Slim version.  Slim-Views 0.1.0 is the
only tagged release I see on github, but even in the current master branch
I don't see an all() function.

Aha - now I see it!  In the master branch of Slim.  I guess all() was added
after 2.2.0.  I'll have to set my minimum stability to dev to use Twig, or
just stick with the hack of replacing the method call like in this patch.

On Tue, Nov 26, 2013 at 6:24 PM, Andrew Smith notifications@github.comwrote:

> What version of Slim are you using? Slim Views is only to be used with
> 2.2+.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/codeguy/Slim-Views/pull/9#issuecomment-29345599
> .

## 

Vic Metcalfe
(647) 977-5389

**Comment by silentworks** [comment]
You can use Slim Extras for anything before 2.3. Not sure why composer allowed you to install 2.2.0 with Slim Views since the requirement says 2.3.0 or greater.

**Comment by silentworks** [comment]
I just had a look and realize that 0.1.0 tag was set to Slim 2.0.0, my mistake there.

**Comment by zymsys** [comment]
No problem - glad to know I'm not losing my mind!

On Tue, Nov 26, 2013 at 6:40 PM, Andrew Smith notifications@github.comwrote:

> I just had a look and realize that 0.1.0 tag was set to Slim 2.0.0, my
> mistake there.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/codeguy/Slim-Views/pull/9#issuecomment-29346576
> .

## 

Vic Metcalfe
(647) 977-5389

**Pull request closed without merging**
